/** How each performance metric should be rendered. */
export type MetricFormat = "percent" | "points" | "ratio" | "count";

export const METRIC_FORMAT: Record<string, MetricFormat> = {
  totalReturn: "percent",
  annualizedReturn: "percent",
  maxDrawdown: "percent",
  winRate: "percent",
  exposure: "percent",
  pctMonths: "percent",
  wrLong: "percent",
  wrShort: "percent",
  benchmarkReturn: "percent",
  netPoints: "points",
  maxDrawdownPoints: "points",
  expectancy: "points",
  avgWin: "points",
  avgLoss: "points",
  longPnl: "points",
  shortPnl: "points",
  sharpe: "ratio",
  sortino: "ratio",
  calmar: "ratio",
  profitFactor: "ratio",
  payoff: "ratio",
  ulcer: "ratio",
  upi: "ratio",
  equityR2: "ratio",
  trades: "count",
  maxConsecutiveLosses: "count",
};

/** Display order: percentage headline first, then points, then ratios. */
export const METRIC_ORDER = [
  "totalReturn",
  "annualizedReturn",
  "maxDrawdown",
  "winRate",
  "profitFactor",
  "payoff",
  "sharpe",
  "sortino",
  "calmar",
  "ulcer",
  "upi",
  "expectancy",
  "netPoints",
  "maxDrawdownPoints",
  "avgWin",
  "avgLoss",
  "longPnl",
  "shortPnl",
  "wrLong",
  "wrShort",
  "exposure",
  "pctMonths",
  "equityR2",
  "trades",
  "maxConsecutiveLosses",
  "benchmarkReturn",
] as const;
