"""Full names of the built-in indicators.

pandas-ta exposes each indicator under a short function name (`rsi`, `cksp`),
and the catalogue used to show that name upper-cased. The first line of the
library's docstrings is not a usable substitute: it carries typos ("Forcast",
"Average Average"), stray marks ("© 2013", "*beta*") and inconsistent casing.
This table is the display name, written once: the full name followed by the
conventional abbreviation where one exists.
"""

from __future__ import annotations

FULL_NAMES: dict[str, str] = {
    # ---------- Candles ----------
    "cdl_doji": "Doji Candle (CDL_DOJI)",
    "cdl_inside": "Inside Bar (CDL_INSIDE)",
    "cdl_pattern": "Candlestick Patterns (CDL_PATTERN)",
    "cdl_z": "Z-Score Candles (CDL_Z)",
    "ha": "Heikin Ashi (HA)",
    # ---------- Cycles ----------
    "dsp": "Detrended Synthetic Price (DSP)",
    "ebsw": "Even Better Sinewave (EBSW)",
    "ht_dcperiod": "Hilbert Transform – Dominant Cycle Period (HT_DCPERIOD)",
    "ht_dcphase": "Hilbert Transform – Dominant Cycle Phase (HT_DCPHASE)",
    "ht_phasor": "Hilbert Transform – Phasor Components (HT_PHASOR)",
    "ht_sine": "Hilbert Transform – Sinewave (HT_SINE)",
    "ht_trendmode": "Hilbert Transform – Trend vs Cycle Mode (HT_TRENDMODE)",
    "msw": "Mesa Sine Wave (MSW)",
    # ---------- Momentum ----------
    "ao": "Awesome Oscillator (AO)",
    "apo": "Absolute Price Oscillator (APO)",
    "bias": "Bias (BIAS)",
    "bop": "Balance of Power (BOP)",
    "brar": "Emotion Index BR/AR (BRAR)",
    "cci": "Commodity Channel Index (CCI)",
    "cfo": "Chande Forecast Oscillator (CFO)",
    "cg": "Center of Gravity (CG)",
    "cmo": "Chande Momentum Oscillator (CMO)",
    "coppock": "Coppock Curve (COPC)",
    "cti": "Correlation Trend Indicator (CTI)",
    "dm": "Directional Movement (DM)",
    "er": "Efficiency Ratio (ER)",
    "eri": "Elder Ray Index (ERI)",
    "fisher": "Fisher Transform (FISHT)",
    "fosc": "Forecast Oscillator (FOSC)",
    "inertia": "Inertia (INERTIA)",
    "kdj": "KDJ Indicator (KDJ)",
    "kst": "Know Sure Thing (KST)",
    "lrsi": "Laguerre Relative Strength Index (LRSI)",
    "macd": "Moving Average Convergence Divergence (MACD)",
    "macdext": "MACD with Controllable Moving Average Type (MACDEXT)",
    "macdfix": "MACD with Fixed Periods (MACDFIX)",
    "mom": "Momentum (MOM)",
    "pgo": "Pretty Good Oscillator (PGO)",
    "po": "Projection Oscillator (PO)",
    "ppo": "Percentage Price Oscillator (PPO)",
    "psl": "Psychological Line (PSL)",
    "pvo": "Percentage Volume Oscillator (PVO)",
    "qqe": "Quantitative Qualitative Estimation (QQE)",
    "roc": "Rate of Change (ROC)",
    "rocp": "Rate of Change Percentage (ROCP)",
    "rocr": "Rate of Change Ratio (ROCR)",
    "rocr100": "Rate of Change Ratio × 100 (ROCR100)",
    "rsi": "Relative Strength Index (RSI)",
    "rsx": "Relative Strength Xtra (RSX)",
    "rvgi": "Relative Vigor Index (RVGI)",
    "slope": "Slope (SLOPE)",
    "smc_sweep": "Smart Money Concept Liquidity Sweep (SMC_SWEEP)",
    "smi": "SMI Ergodic Indicator (SMI)",
    "squeeze": "Squeeze (SQZ)",
    "squeeze_pro": "Squeeze Pro (SQZPRO)",
    "stc": "Schaff Trend Cycle (STC)",
    "stoch": "Stochastic Oscillator (STOCH)",
    "stochf": "Fast Stochastic Oscillator (STOCHF)",
    "stochrsi": "Stochastic RSI (STOCHRSI)",
    "td_seq": "TD Sequential (TD_SEQ)",
    "trix": "Triple Exponential Average (TRIX)",
    "trixh": "TRIX Histogram (TRIXH)",
    "tsi": "True Strength Index (TSI)",
    "uo": "Ultimate Oscillator (UO)",
    "vwmacd": "Volume-Weighted MACD (VWMACD)",
    "willr": "Williams %R (WILLR)",
    # ---------- Moving averages & price transforms ----------
    "alma": "Arnaud Legoux Moving Average (ALMA)",
    "avgprice": "Average Price (AVGPRICE)",
    "dema": "Double Exponential Moving Average (DEMA)",
    "ema": "Exponential Moving Average (EMA)",
    "fwma": "Fibonacci Weighted Moving Average (FWMA)",
    "hilo": "Gann High-Low Activator (HILO)",
    "hl2": "Median Price (HL2)",
    "hlc3": "Typical Price (HLC3)",
    "hma": "Hull Moving Average (HMA)",
    "ht_trendline": "Hilbert Transform – Instantaneous Trendline (HT_TRENDLINE)",
    "hwma": "Holt-Winters Moving Average (HWMA)",
    "ichimoku": "Ichimoku Kinkō Hyō (ICHIMOKU)",
    "jma": "Jurik Moving Average (JMA)",
    "kama": "Kaufman Adaptive Moving Average (KAMA)",
    "linreg": "Linear Regression Moving Average (LINREG)",
    "linregangle": "Linear Regression Angle (LINREGANGLE)",
    "linregintercept": "Linear Regression Intercept (LINREGINTERCEPT)",
    "linregslope": "Linear Regression Slope (LINREGSLOPE)",
    "mama": "MESA Adaptive Moving Average (MAMA)",
    "mavp": "Moving Average with Variable Period (MAVP)",
    "mcgd": "McGinley Dynamic (MCGD)",
    "medprice": "Median Price (MEDPRICE)",
    "midpoint": "Midpoint over Period (MIDPOINT)",
    "midprice": "Midpoint Price over Period (MIDPRICE)",
    "mmar": "Madrid Moving Average Ribbon (MMAR)",
    "ohlc4": "Average of Open, High, Low, Close (OHLC4)",
    "pwma": "Pascal Weighted Moving Average (PWMA)",
    "rainbow": "Rainbow Moving Averages (RAINBOW)",
    "rma": "Wilder's Moving Average (RMA)",
    "sinwma": "Sine Weighted Moving Average (SINWMA)",
    "sma": "Simple Moving Average (SMA)",
    "ssf": "Ehlers Super Smoother Filter (SSF)",
    "supertrend": "Supertrend (SUPERTREND)",
    "swma": "Symmetric Weighted Moving Average (SWMA)",
    "t3": "Tillson T3 Moving Average (T3)",
    "tema": "Triple Exponential Moving Average (TEMA)",
    "trima": "Triangular Moving Average (TRIMA)",
    "tsf": "Time Series Forecast (TSF)",
    "typprice": "Typical Price (TYPPRICE)",
    "vidya": "Variable Index Dynamic Average (VIDYA)",
    "vwap": "Volume-Weighted Average Price (VWAP)",
    "vwma": "Volume-Weighted Moving Average (VWMA)",
    "wcp": "Weighted Closing Price (WCP)",
    "wma": "Weighted Moving Average (WMA)",
    "zlma": "Zero-Lag Moving Average (ZLMA)",
    # ---------- Performance ----------
    "drawdown": "Drawdown (DD)",
    "log_return": "Logarithmic Return (LOGRET)",
    "percent_return": "Percentage Return (PCTRET)",
    # ---------- Statistics ----------
    "entropy": "Entropy (ENTP)",
    "kurtosis": "Rolling Kurtosis (KURT)",
    "mad": "Rolling Mean Absolute Deviation (MAD)",
    "md": "Mean Deviation (MD)",
    "median": "Rolling Median (MEDIAN)",
    "quantile": "Rolling Quantile (QTL)",
    "skew": "Rolling Skewness (SKEW)",
    "stderr": "Standard Error (STDERR)",
    "stdev": "Rolling Standard Deviation (STDEV)",
    "tos_stdevall": "Standard Deviation Channel – All Bars (TOS_STDEVALL)",
    "variance": "Rolling Variance (VAR)",
    "zscore": "Rolling Z-Score (ZSCORE)",
    # ---------- Trend ----------
    "adx": "Average Directional Index (ADX)",
    "adxr": "Average Directional Index Rating (ADXR)",
    "amat": "Archer Moving Averages Trends (AMAT)",
    "aroon": "Aroon and Aroon Oscillator (AROON)",
    "chop": "Choppiness Index (CHOP)",
    "cksp": "Chande Kroll Stop (CKSP)",
    "cpr": "Central Pivot Range (CPR)",
    "decay": "Linear Decay (DECAY)",
    "decreasing": "Decreasing Series (DEC)",
    "dpo": "Detrended Price Oscillator (DPO)",
    "dx": "Directional Movement Index (DX)",
    "edecay": "Exponential Decay (EDECAY)",
    "increasing": "Increasing Series (INC)",
    "minus_dm": "Minus Directional Movement (−DM)",
    "plus_dm": "Plus Directional Movement (+DM)",
    "pmax": "Profit Maximizer (PMAX)",
    "psar": "Parabolic Stop and Reverse (PSAR)",
    "qstick": "Q Stick (QSTICK)",
    "sarext": "Parabolic SAR Extended (SAREXT)",
    "ttm_trend": "TTM Trend (TTM_TRND)",
    "vhf": "Vertical Horizontal Filter (VHF)",
    "vortex": "Vortex Indicator (VTX)",
    # ---------- Volatility ----------
    "aberration": "Aberration (ABER)",
    "accbands": "Acceleration Bands (ACCBANDS)",
    "atr": "Average True Range (ATR)",
    "avolume": "Annualised Historical Volatility (AVOL)",
    "bbands": "Bollinger Bands (BBANDS)",
    "ce": "Chandelier Exit (CE)",
    "cvi": "Chaikin Volatility (CVI)",
    "donchian": "Donchian Channels (DC)",
    "hvol": "Historical Volatility (HVOL)",
    "hwc": "Holt-Winters Channel (HWC)",
    "kc": "Keltner Channels (KC)",
    "massi": "Mass Index (MASSI)",
    "natr": "Normalized Average True Range (NATR)",
    "pdist": "Price Distance (PDIST)",
    "rvi": "Relative Volatility Index (RVI)",
    "thermo": "Elder's Thermometer (THERMO)",
    "true_range": "True Range (TR)",
    "ui": "Ulcer Index (UI)",
    # ---------- Volume ----------
    "ad": "Accumulation/Distribution Line (AD)",
    "adosc": "Chaikin Accumulation/Distribution Oscillator (ADOSC)",
    "aobv": "Archer On-Balance Volume (AOBV)",
    "cmf": "Chaikin Money Flow (CMF)",
    "efi": "Elder's Force Index (EFI)",
    "emv": "Ease of Movement (EMV)",
    "eom": "Ease of Movement (EOM)",
    "kvo": "Klinger Volume Oscillator (KVO)",
    "marketfi": "Market Facilitation Index (MARKETFI)",
    "mfi": "Money Flow Index (MFI)",
    "nvi": "Negative Volume Index (NVI)",
    "obv": "On-Balance Volume (OBV)",
    "pvi": "Positive Volume Index (PVI)",
    "pvol": "Price-Volume (PVOL)",
    "pvr": "Price Volume Rank (PVR)",
    "pvt": "Price-Volume Trend (PVT)",
    "vfi": "Volume Flow Indicator (VFI)",
    "vosc": "Volume Oscillator (VOSC)",
    "wad": "Williams Accumulation/Distribution (WAD)",
}


def full_name(indicator_id: str) -> str:
    """The display name; an id the table does not know keeps its short form."""
    return FULL_NAMES.get(indicator_id, indicator_id.upper())
